.TH TINTWIZARD 1 "October 08, 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
tintwizard \- graphical tint2 configuration utility
.SH SYNOPSIS
.B tintwizard [-c file]
.SH DESCRIPTION
tintwizard is a GTK based utility used to create or
modify tint2 config files.
.SH OPTIONS
.TP
\fB\-c\fR \fIfile\fR
load configuration from this file
.SH AUTHOR
tintwizard was written by Euan Freeman <euan04@gmail.com>.
.PP
This manual page was written by Sebastian Reichel <sre@debian.org>,
for the Debian project (but may be used by others).
