.TH TINT2CONF 1 "October 08, 2010"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
tint2conf \- tint configuration manager
.SH SYNOPSIS
.B tint2conf
.SH DESCRIPTION
tint2conf is a configuration previewer for tint2, which can
invoke tintwizard, a graphical configuration utility for
tint2 configuration files.
.SH OPTIONS
tint2conf takes no parameters.
.SH AUTHOR
tint2conf was written by the tint2 team.
.PP
This manual page was written by Sebastian Reichel <elektranox@gmail.com>,
for the Debian project (but may be used by others).
.SH SEE ALSO
tintwizard(1)
